# Sample_4

In [1]:
import numpy as np
import matplotlib.pyplot as plt

data = np.genfromtxt('Sample_4_Stars_blue_314248_lines.txt')

xi = data[:,0]
ei = data[:,1]
n = data[:,2]
maybe_rmag = data[:,3]

starb_n = np.unique(n)

In [9]:
len(starb_n)

1963

In [3]:




data_qso = np.genfromtxt('Sample_4_QSO_721283_lines.txt', dtype=str)
nq = data_qso[:,2]
qso_uniq = np.unique(nq)

In [4]:
len(qso_uniq)

4652

# Redo version, using exactly the same StarB, StarR, QSO names 

In [6]:
data_new = np.genfromtxt('/astro/store/scratch/tmp/suberlak/SF_Samples/Sample_4_redo/Sample_starB_tau_0-1.7_280344_lines_1760_objects.txt')

In [7]:
starb1_n = np.unique(data_new[:,3])

In [8]:
len(starb1_n)

1760

In [12]:
np.sum(np.in1d(starb_n, starb1_n))

394

# Make a sample with exactly the same red, blue stars as well as qso as Sample_4... 

In [71]:
datab = np.genfromtxt('Sample_4_Stars_blue_314248_lines.txt')
nb = datab[:,2]
starsb_uniq = np.unique(nb)

datar = np.genfromtxt('Sample_4_Stars_red_373306_lines.txt')
nr = datar[:,2]
starsr_uniq = np.unique(nr)

data_qso = np.genfromtxt('Sample_4_QSO_721283_lines.txt', dtype=str)
nq = data_qso[:,2]
qso_uniq = np.unique(nq)



In [109]:
np.savetxt('Sample_4_stars_b_unique_names.txt',starsb_uniq.astype(str), fmt = "%s")
np.savetxt('Sample_4_stars_r_unique_names.txt', starsr_uniq.astype(str), fmt="%s")
np.savetxt('Sample_4_qso_unique_names.txt', qso_uniq.astype(str), fmt="%s")



In [24]:
# how many objects is there in this sample ? 

len(starsb_uniq)

1963

In [25]:
len(starsr_uniq)

2266

In [40]:
len(qso_uniq)

4652

In [52]:
datab[:,3]

array([ 17.923,  17.923,  17.923, ...,  18.466,  18.466,  18.466])

In [38]:
qso[:,3]

array([ 18.025,  18.025,  18.025, ...,  19.932,  19.932,  19.932])

In [45]:
def get_qso_catalog(catalog):
    if catalog == 's82drw':
        File = 'CRTS_SDSS_cross_matched_qso_s82drw_catalog.txt'
    if catalog == 'DB_QSO':
        File = 'CRTS_SDSS_cross_matched_qso_DB_QSO_catalog.txt'
    colnames = open(File,'r').read().splitlines()[0][1:].split()
    datatable = np.genfromtxt(File)
    qso_catalog = {}
    print 'Zipping CRTS-SDSS quasars catalog from ', File, ' ...'
    for label, column in zip(colnames, datatable.T):
        qso_catalog[label] = column
    
    qso_names = np.genfromtxt('CRTS_SDSS_cross_matched_qso_names.txt', dtype=str)    
    for i in range(len(qso_names)):
        qso_names[i] = qso_names[i][4:-4]
    print 'Read in ', len(qso_catalog['redshift']), ', quasars from CRTS'
    return  colnames, qso_catalog, qso_names
    
def get_stars_catalog():
    File = 'CRTS_SDSS_cross_matched_stars_catalog.txt'
    colnames = open(File,'r').read().splitlines()[0][1:].split()
    datatable = np.genfromtxt(File)
    stars_catalog = {}
    print 'zipping CRTS-SDSS stars catalog...'
    for label, column in zip(colnames, datatable.T):
        stars_catalog[label] = column
        
    return  colnames, stars_catalog

cols1, qso_cat, qso_names = get_qso_catalog(catalog='DB_QSO') 
cols2 , star_cat= get_stars_catalog()

Zipping CRTS-SDSS quasars catalog from  CRTS_SDSS_cross_matched_qso_DB_QSO_catalog.txt  ...
Read in  7601 , quasars from CRTS
zipping CRTS-SDSS stars catalog...


In [46]:
star_cat[]

{'CRTS_M': array([ 20.62613,  18.58793,  19.61459, ...,  14.78404,  18.37912,
         19.60277]),
 'CRTS_Merr': array([ 0.40859,  0.07427,  0.21857, ...,  0.03049,  0.06774,  0.1417 ]),
 'N_rows': array([  20.,   82.,   37., ...,  101.,   77.,   39.]),
 'crts_id': array([ 807805.,  212429.,  473621., ...,  705958.,  188223.,  348807.]),
 'dec_CRTS': array([ 0.04909,  0.59888,  0.91459, ...,  1.0105 ,  1.08605, -0.89175]),
 'dec_SDSS': array([ 0.04909,  0.59888,  0.91459, ...,  1.0105 ,  1.08605, -0.89175]),
 'g_Nobs': array([  6.,  13.,   5., ...,   8.,  13.,   7.]),
 'g_mMed': array([ 21.896,  20.064,  22.467, ...,  15.241,  20.312,  21.165]),
 'i_mMed': array([ 20.214,  18.116,  19.887, ...,  14.623,  17.681,  18.682]),
 'mjd_N': array([  20.,   82.,   37., ...,  101.,   77.,   39.]),
 'mjd_span': array([ 2969.,  2937.,  3065., ...,  3083.,  2937.,  3034.]),
 'r_mMed': array([ 20.72 ,  18.714,  20.977, ...,  14.789,  18.97 ,  19.688]),
 'ra_CRTS': array([ 333.8186 ,   41.31015,  313

In [56]:
cat_starb_gmags = [star_cat['g_mMed'][star_cat['crts_id'] == star][0]  for star in starsb_uniq ]

In [53]:
sample4_starb_gmags =  [datab[:,3][datab[:,2] == star][0] for star in starsb_uniq]

In [59]:
# I can confirm : for each star, the magnitude reported in Sample 4 is exactly the same as 
# the catalog gmag entry for a star of that same name  

# Thus I can use the magnitudes from Sample_4  as the reported magnitudes,
# or I can pull out magnitudes from the catalog - doesn't make a difference for Blue Stars  

np.sum(np.array(sample4_starb_gmags) - np.array(cat_starb_gmags))

0.0

In [60]:
# Check that the same holds for Red Stars 
cat_starr_gmags = [star_cat['g_mMed'][star_cat['crts_id'] == star][0]  for star in starsr_uniq ]
sample4_starr_gmags =  [datar[:,3][datar[:,2] == star][0] for star in starsr_uniq]

In [62]:
np.sum(np.array(sample4_starr_gmags) - np.array(cat_starr_gmags))
#Indeed , it does hold for red stars - check quasars now ! 

0.0

In [ ]:
# Check QSO : are the magnitudes reported in the file the same as  the catalog gmag entires 
# for quasars of that name  ? 

cat_qso_gmags = [star_cat['g_mMed'][star_cat['crts_id'] == qso][0]  for qso in qso_uniq ]

In [63]:
qso_cat.keys()

['N_rows',
 'g',
 'redshift',
 'i',
 'ra_SDSS',
 'dec_CRTS',
 'mjd_uniq_N',
 'r',
 'u',
 'ra_CRTS',
 'CRTS_avg_m',
 'dec_SDSS',
 'z',
 'mjd_span',
 'CRTS_avg_e']

In [95]:
qso_mag = data_qso[:,3].astype(float)
cat_qso_gmags = [qso_cat['r'][qso_names == qso][0] for qso in qso_uniq]

In [89]:
sample4_qso_gmags =  [qso_mag[data_qso[:,2] == qso][0] for qso in qso_uniq]

In [97]:
# The thing : the mags reported for QSO  are SDSS r_mags   instead of SDSS g_mags    !  
np.sum(np.array(sample4_qso_gmags) - np.array(cat_qso_gmags))

0.0

In [101]:
a =np.loadtxt('Sample_4_qso_unique_names.txt', dtype=str)

In [105]:
b = np.loadtxt('Sample_4_stars_b_unique_names.txt')

In [106]:
b

array([  2.51000000e+02,   3.36600000e+03,   3.98900000e+03, ...,
         1.00528900e+06,   1.00621400e+06,   1.00672300e+06])